export const Books = [
  {
    id: 1,
    title: 'Its Ends with us',
    author: 'Harper Lee',
    publication_year: 1960,
    genre: [ 'Fiction', 'Classic' ],
    description: 'A classic novel depicting racial injustice in the American South.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1688011813i/27362503._SX150_.jpg',
    rating:'4.2',
  },
  {
    id: 2,
    title: 'The Subtle Art',
    author: 'George Orwell',
    publication_year: 1949,
    genre: [ 'Dystopian', 'Science Fiction' ],
    description: 'A dystopian novel portraying a totalitarian society.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1465761302i/28257707._SX150_.jpg',
    rating:'4.6',
  },
  {
    id: 3,
    title: 'A court of Mist',
    author: 'Jane Austen',
    publication_year: 1813,
    genre: [ 'Classic', 'Romance' ],
    description: 'A classic novel exploring themes of love, marriage, and social norms.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1620325671i/50659468._SX150_.jpg',
    rating:'4.9',
  },
  {
    id: 4,
    title: 'Harry Potter',
    author: 'F. Scott Fitzgerald',
    publication_year: 1925,
    genre: [ 'Fiction', 'Classic' ],
    description: 'A tale of the American Dream, wealth, and love during the Roaring Twenties.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1470082995i/29056083._SX150_.jpg',
    rating:'4.1',
  },
  {
    id: 5,
    title: 'Caraval',
    author: 'Herman Melville',
    publication_year: 1851,
    genre: [ 'Fiction', 'Adventure' ],
    description: "The epic tale of Captain Ahab's obsession with the white whale.",
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1465563623i/27883214._SX150_.jpg',
    rating:'3.5',
  },
  {
    id: 6,
    title: 'The Women in Cabin',
    author: 'J.R.R. Tolkien',
    publication_year: 1954,
    genre: [ 'Fantasy', 'Adventure' ],
    description: 'An epic fantasy saga about the quest to destroy the One Ring.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1465878007i/28187230._SX150_.jpg',
    rating:'3.8',
  },
  {
    id: 7,
    title: 'Trevor',
    author: 'J.D. Salinger',
    publication_year: 1951,
    genre: [ 'Fiction', 'Coming-of-age' ],
    description: "A classic coming-of-age novel following Holden Caulfield's journey.",
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1473867911i/29780253._SX150_.jpg',
    rating:'4.7',
  },
  {
    id: 8,
    title: 'When Breath Becomes Air',
    author: 'J.R.R. Tolkien',
    publication_year: 1937,
    genre: [ 'Fantasy', 'Adventure' ],
    description: "The prequel to The Lord of the Rings, following Bilbo Baggins' journey.",
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1492677644i/25899336._SX150_.jpg',
    rating:'4.8',
  },
  {
    id: 9,
    title: 'Crooked Kingdom ',
    author: 'Gabriel Garcia Marquez',
    publication_year: 1967,
    genre: [ 'Magical Realism', 'Literary Fiction' ],
    description: 'A multi-generational saga of the Buendía family in the fictional town of Macondo.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1456172607i/22299763._SX150_.jpg',
    rating:'4.6',
  },
  {
    id: 10,
    title: 'Dark Matter',
    author: 'Leo Tolstoy',
    publication_year: 1869,
    genre: [ 'Historical Fiction', 'Epic' ],
    description: 'A monumental work depicting the events of Russian society during the Napoleonic era.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1472119680i/27833670._SX150_.jpg',
    rating:'4.5',
  },
  {
    id: 11,
    title: 'One True Loves',
    author: 'Homer',
    publication_year: '8th century BCE',
    genre: [ 'Epic', 'Mythology' ],
    description: "An ancient Greek epic poem recounting Odysseus' ten-year journey home after the Trojan War.",
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1559960507i/27189194._SX150_.jpg',
    rating:'4.4',
  },
  {
    id: 12,
    title: 'Behind Closed Doors',
    author: 'Dante Alighieri',
    publication_year: '1320',
    genre: [ 'Epic', 'Poetry' ],
    description: 'An epic poem that follows the journey of the soul through Hell, Purgatory, and Heaven.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1458854462i/29437949._SX80_.jpg',
    rating:'4.6',
  },
  {
    id: 13,
    title: 'The Hating Game',
    author: 'Fyodor Dostoevsky',
    publication_year: 1880,
    genre: [ 'Classic', 'Philosophical Fiction' ],
    description: 'A complex novel exploring themes of spirituality, morality, and human nature.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1481566824i/27213238._SX80_.jpg',
    rating:'4.3',
  },
  {
    id: 14,
    title: 'The Couple Next Door',
    author: 'Fyodor Dostoevsky',
    publication_year: 1866,
    genre: [ 'Classic', 'Psychological Fiction' ],
    description: 'A psychological thriller revolving around guilt, conscience, and redemption.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1471502242i/28815474._SX80_.jpg',
    rating:'4.7',
  },
  {
    id: 15,
    title: 'Punk 57',
    author: 'Oscar Wilde',
    publication_year: 1890,
    genre: [ 'Gothic', 'Philosophical Fiction' ],
    description: 'A novel about a man whose portrait ages while he retains his youth and beauty.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1689301728i/41021967._SX80_.jpg',
    rating:'4.9',
  },
  {
    id: 16,
    title: 'A Gentleman in Moscow',
    author: 'Aldous Huxley',
    publication_year: 1932,
    genre: [ 'Dystopian', 'Science Fiction' ],
    description: 'A dystopian vision of a future society obsessed with pleasure and conformity.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1718915012i/34066798._SX80_.jpg',
    rating:'5',
  },
  {
    id: 17,
    title: 'The Underground Railroad',
    author: 'Alexandre Dumas',
    publication_year: 1844,
    genre: [ 'Adventure', 'Historical Fiction' ],
    description: 'An adventure novel of revenge, love, and redemption set in the early 19th century.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1493178362i/30555488._SX80_.jpg',
    rating:'4.5',
  },
  {
    id: 18,
    title: 'Empire of Storms ',
    author: 'Leo Tolstoy',
    publication_year: 1877,
    genre: [ 'Classic', 'Romance' ],
    description: 'A tragic love story set against the backdrop of Russian high society.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1676979605i/76713323._SX80_.jpg',
    rating:'5',
  },
  {
    id: 19,
    title: 'Beartown ',
    author: 'Paulo Coelho',
    publication_year: 1988,
    genre: [ 'Fiction', 'Philosophical' ],
    description: "A philosophical novel about a shepherd boy's journey to find his personal legend.",
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1482108618i/33413128._SX80_.jpg',
    rating:'4.6',
  },
  {
    id: 20,
    title: 'The Sun Is Also a Star',
    author: 'Mark Twain',
    publication_year: 1884,
    genre: [ 'Adventure', 'Satire' ],
    description: "A satirical novel following Huck Finn's journey down the Mississippi River.",
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1459793538i/28763485._SX80_.jpg',
    rating:'4',
  },
  {
    id: 21,
    title: 'Homegoing',
    author: 'Homer',
    publication_year: '8th century BCE',
    genre: [ 'Epic', 'Mythology' ],
    description: 'An ancient Greek epic poem about the Trojan War and the hero Achilles.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1448108591i/27071490._SX80_.jpg',
    rating:'3',
  },
  {
    id: 22,
    title: 'Hillbilly Elegy',
    author: 'J.R.R. Tolkien',
    publication_year: 1954,
    genre: [ 'Fantasy', 'Adventure' ],
    description: 'A thrilling epic about the quest to destroy the One Ring and save Middle-earth from the dark lord Sauron.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1463569814i/27161156._SX80_.jpg',
    rating:'2',
  },
  {
    id: 23,
    title: 'A Thousand Boy Kisses',
    author: 'Miguel de Cervantes',
    publication_year: 1605,
    genre: [ 'Classic', 'Satire' ],
    description: 'A satirical novel about a deluded knight and his faithful squire, Sancho Panza.',
    cover_image: 'https://cdn.pixabay.com/photo/2015/11/19/21/10/glasses-1052010_640.jpg',
    rating:'2.5',
  },
  {
    id: 24,
    title: 'Scythe',
    author: 'Mary Shelley',
    publication_year: 1818,
    genre: [ 'Gothic', 'Science Fiction' ],
    description: 'A novel about the creation of a monster and the consequences of playing god.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1456172676i/28954189._SX80_.jpg',
    rating:'3.5',
  },
  {
    id: 25,
    title: "Shoe Dog",
    author: 'Lewis Carroll',
    publication_year: 1865,
    genre: [ 'Fantasy', "Children's Literature" ],
    description: 'A whimsical tale about a girl named Alice who falls into a magical world.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1457284880i/27220736._SX80_.jpg',
    rating:'3.9',
  },
  {
    id: 26,
    title: 'Lalic Girls',
    author: 'Antoine de Saint-Exupéry',
    publication_year: 1943,
    genre: [ 'Fable', "Children's Literature" ],
    description: "A philosophical novella about a young prince's journey through the universe.",
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1462850258i/25893693._SX80_.jpg',
    rating:'4.6',
  },
  {
    id: 27,
    title: 'Glass Sword',
    author: 'Markus Zusak',
    publication_year: 2005,
    genre: [ 'Historical Fiction', 'War' ],
    description: 'A story of a girl living in Nazi Germany, narrated by Death.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1436460934i/23174274._SX80_.jpg',
    rating:'4.9',
  },
  {
    id: 28,
    title: 'Girl in Peace',
    author: 'Kurt Vonnegut',
    publication_year: 1969,
    genre: [ 'Satire', 'Science Fiction' ],
    description: 'An anti-war novel that mixes science fiction and dark humor.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1469509467i/29236380._SX80_.jpg',
    rating:'5',
  },
  {
    id: 29,
    title: 'Heartless',
    author: 'John Steinbeck',
    publication_year: 1939,
    genre: [ 'Historical Fiction', 'Social Commentary' ],
    description: 'A novel about the plight of migrant workers during the Great Depression.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1477740245i/18584855._SX80_.jpg',
    rating:'4.1',
  },
  {
    id: 30,
    title: 'Salt to sea',
    author: 'Ray Bradbury',
    publication_year: 1953,
    genre: [ 'Dystopian', 'Science Fiction' ],
    description: 'A dystopian novel depicting a future society where books are banned.',
    cover_image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1437084512i/25614492._SX80_.jpg',
    rating:'4.4',
  },
  {
    id: 31,
    title: 'The Lord of the Flies',
    author: 'William Golding',
    publication_year: 1954,
    genre: [ 'Dystopian', 'Psychological Fiction' ],
    description: 'A novel about a group of British boys stranded on an uninhabited island.',
    cover_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_yggG9mxxqm5LMIPVknOweoGNRg8cgFamGA&s',
    rating:'5',
  },
  {
    id: 32,
    title: "The Hitchhiker's Guide to the Galaxy",
    author: 'Douglas Adams',
    publication_year: 1979,
    genre: [ 'Science Fiction', 'Comedy' ],
    description: 'A comedic science fiction series about the misadventures of Arthur Dent.',
    cover_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtCyGq73Yl8yr0YzSuxuS8-fJUQVGXDgPJRw&s',
    rating:'2.5',
  },
  {
    id: 33,
    title: 'A Tale of Two Cities',
    author: 'Charles Dickens',
    publication_year: 1859,
    genre: [ 'Historical Fiction', 'Classic' ],
    description: 'A historical novel set during the French Revolution, exploring themes of sacrifice and resurrection.',
    cover_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWhh8NZkGr5dMPDBFke865glqUt_iqGME6zg&s',
    rating:'3.5',
  },
  {
    id: 34,
    title: 'The Chronicles of Narnia',
    author: 'C.S. Lewis',
    publication_year: 1950,
    genre: [ 'Fantasy', "Children's Literature" ],
    description: 'A series of fantasy novels set in the magical land of Narnia.',
    cover_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_SvNdhsragJz3KbpcDN5mpJW4jON4DGk7tQ&s',
    rating:'3.5',
  },
  {
    id: 35,
    title: "The Handmaid's Tale",
    author: 'Margaret Atwood',
    publication_year: 1985,
    genre: [ 'Dystopian', 'Feminist Fiction' ],
    description: 'A dystopian novel set in a totalitarian society where women are subjugated.',
    cover_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjUfwxCuU0RUSJjQlxkwEbRkuChTivYMG3l7gKaR8IRwZhVKzIg8_Kq3z3NDyIk8GEB5M&usqp=CAU',
    rating:'4.7',
  },
  {
    id: 36,
    title: 'The Name of the Rose',
    author: 'Umberto Eco',
    publication_year: 1980,
    genre: [ 'Historical Fiction', 'Mystery' ],
    description: 'A medieval mystery novel set in an Italian monastery.',
    cover_image: 'https://thumbs.dreamstime.com/b/reading-books-15549459.jpg',
    rating:'4.5',
  },
  {
    id: 37,
    title: 'The Trial',
    author: 'Franz Kafka',
    publication_year: 1925,
    genre: [ 'Absurdist Fiction', 'Existential' ],
    description: 'A surreal novel exploring themes of guilt, law, and justice.',
    cover_image: 'https://www.wikihow.com/images/a/a3/What-book-should-i-read-quiz-image.png',
    rating:'4.8',
  },
  {
    id: 38,
    title: 'The Kite Runner',
    author: 'Khaled Hosseini',
    publication_year: 2003,
    genre: [ 'Historical Fiction', 'Drama' ],
    description: 'A novel about friendship, redemption, and the impact of war in Afghanistan.',
    cover_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_wMKhVayYbsUZ4euITH0BSL5OBCRLHDfhHQ&s',
    rating:'3.8',
  },
  {
    id: 39,
    title: 'The Pillars of the Earth',
    author: 'Ken Follett',
    publication_year: 1989,
    genre: [ 'Historical Fiction', 'Adventure' ],
    description: 'An epic historical novel set in 12th-century England, centered around the construction of a cathedral.',
    cover_image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLVkQoQOWhpFAizWDDdHkCms2LDvgKrMfEmw&s',
    rating:'4',
  },
  {
    id: 40,
    title: 'The Shadow of the Wind',
    author: 'Carlos Ruiz Zafón',
    publication_year: 2001,
    genre: [ 'Mystery', 'Gothic' ],
    description: 'A mystery novel set in post-war Barcelona, revolving around a forgotten book and its author.',
    cover_image: 'https://img.freepik.com/free-photo/old-books-arrangement-with-copy-space_23-2148898331.jpg',
    rating:'5',
  },
];  
